### ISSUE TITLE
Add stats for Orly's Knesset work

### ISSUE THREAD

**Issue by daonb** [daonb/o14s-www#5]
In Orly's section we need to replace "ציטוטים של אורלי מוועדות הכנסת:" with a paragraph containing some numbers:

- Number of months as a PM
- Number of committee meetings attended
- Number f Plenum meetings attended
- Number of times Orly has spoken in the committees
- Number of words Orly has spoken in the committees

**Comment by OriHoch** [comment]
I'll try to get some stuff from Redash

**Comment by OriHoch** [comment]
all queries include both committee meetings and plenum meeting (they are on the same tables)
* [Open Knesset: find all meetings attended by a specific member](http://data.obudget.org/queries/1057?p_member_name=%D7%90%D7%95%D7%A8%D7%9C%D7%99%20%D7%9C%D7%95%D7%99-%D7%90%D7%91%D7%A7%D7%A1%D7%99%D7%A1)
* [open knesset: all protocol parts where Orly Levy-Abekasis spoke in committee meetings](http://data.obudget.org/queries/1059)

**Comment by daonb** [comment]
Thanks! I filtered out Plenum meetings so the total are:
- 753 committee meetings since Februray 2009
- 347 plenum meetings since August 2012 when oknesset started collecting data
